name: Add issue to project
on:
  issues:
    types:
      - opened
      - transferred
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Add to project board
        uses: actions/add-to-project@75ae529d219964f1ad5c0e8351e4e7c38ed501be
        with:
          project-url: ${{ secrets.QA_TEAM_PROJECT_URL }}
          github-token: ${{ steps.generate_token.outputs.token }}
